### ISSUE TITLE
The number of random walks. 

### ISSUE THREAD

**Issue by HereW** [wanghzccls/ExactSim#1]
In the paper, the number of random walks R = (6 \log n) / (  (1 - \sqrt{c})^4 \epsilon^2). 

However, in the code SimStruct.h, line 106, power_walk_num = (long)((C_value * 0.00001) * (log(vert / delta) / log(2)) / (eps * eps)). 

I wonder what delta means. And whether the number of random walks in the code is enough for the sampling of matrix D or not. 

Thank you!

**Comment by wanghzccls** [comment]
Thanks for your attention! 

In our paper, we set R = (6 \log n) / ( (1 - \sqrt{c})^4 \epsilon^2)=O(logn/eps^2) which is a loose bound. We find that, in practice, setting power_walk_num=((C_value * 0.00001) * (log(vert / delta) / log(2)) / (eps * eps)) is sufficient to achieve a MaxError of 10^-7, where delta=0.01 is the failing probability. You can change power_walk_num back to (6 \log n) / ( (1 - \sqrt{c})^4 \epsilon^2) if you desire an absolute theoretical guarantee.

**Comment by HereW** [comment]
Got it! Thank you for your answer.
